spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

turkraft:
  springfilter:
    localdatetimeformatter:
      pattern: yyyy-MM-dd'T'HH:mm:ss.SSSXXX

sts:
  email:
    url: